site_name: Research Developer Cloud
repo_url: https://github.com/nesi/research-developer-cloud
repo_name: nesi/research-developer-cloud
site_dir: public
theme:
  name: material
  custom_dir: overrides
  favicon: assets/icons/favicon_reannz.ico
  language: en
  logo: assets/icons/logo_reannz.svg
  palette:
      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - content.code.copy
    - content.action.edit
    - header.site_name_homepage
    
hooks:
  - mkdocs_hooks.py
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
      title: On this page
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets: null
  - md_in_html
  - neoteroi.cards
  - neoteroi.timeline

plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - open-in-new-tab
  - awesome-nav:
      filename: .pages.yml
 # - git-authors
  - tags:
      tags: false
  - macros:
      on_error_fail: true
      verbose: false
extra:
  slurm: slurm-25.05.6
  project_code: nesi99991
  working_directory: ["/nesi/nobackup", "nesi99991", "introhpc2603"]
  example_script: "example_script"
  exercise: "https://docs.google.com/spreadsheets/d/1D5PnhE6iJOB3ZKkDCiBHnk5CNZlhmj_gS-IXKGkkVoI/edit?usp=sharing"
  status: 
  - deprecated
  - new
  - tutorial
  analytics:
    provider: google
    property: G-C9SP9NWT3Z
extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/neoteroi-cards.css
  - assets/stylesheets/theme.css
extra_javascript:
  - assets/javascripts/general.js
