nav:
  - index.md
  - launch-and-manage-instances
  - upload-and-manage-images
  - create-and-manage-volumes
  - create-and-manage-networks
  - create-and-manage-identity
  - create-and-manage-keypairs     
  - create-and-manage-object-storage
  - set-up-your-cli-environment
  - ...
